---
title: "lab2"
output: html_document
date: "2024-09-14"
---
## 1 Hidden Markov Model
```{r}
set.seed(123)
library(HMM)

states = as.character(0:9)
emissionSymbols = as.character(0:9)

transitionProb = matrix(0,nrow = 10, ncol = 10)
for (j in 1:10) {
  transitionProb[j,j] = 0.5
  transitionProb[j,j%%10 +1 ] = 0.5
}
print(transitionProb)

emissionProb = matrix(0,nrow = 10, ncol = 10)
for (j in 1:10) {
  for (i in 1:5) {
    emissionProb[(j+i-4)%%10+1,j] = 0.2
  }
}
print(emissionProb)

startProb = rep(0.1,10)

hmm = initHMM(States = states, Symbols = emissionSymbols, 
              startProbs = startProb, transProbs = transitionProb, 
              emissionProbs = emissionProb)
```
## 2 Simulate 100 time steps
```{r}
nIter = 100
simulation = simHMM(hmm, nIter)
print(simulation)
```
## 3 Filtering, smoothing and most probable path
```{r}

alpha = exp(forward(hmm, simulation$observation))
beta = exp(backward(hmm, simulation$observation))

#filtered distribution

filtered_probs = matrix(0, nrow=10, ncol=nIter)

#normalize forward probabilities to get the filtered probabilities
for (t in 1:nIter) {
  filtered_probs[, t] <- alpha[,t] / sum(alpha[,t])
}

print("Filtered Probabilities:")
print(filtered_probs)

#smoothed probability distribution


#most probable path via viterbi
```

