---
title: "Hjalmar_oct2023"
author: "Hjalmar Öhman"
date: "2024-10-22"
output: pdf_document
---

## 1
```{r}
library(bnlearn)
both = model2network("[U][Ch|U][Ah|Ch][Bh|Ch][Dh|Ah:Bh][C|U][A|C][B|C][D|A:B]")
graphviz.plot(both)

U = matrix(c(0.5, 0.5), nrow = 1, ncol = 2)
dim(U) = c(2)
dimnames(U) = list("U" = c("U0", "U1"))

C = matrix(c(0.9,0.1,0.1,0.9), nrow = 2, ncol=2)
dim(C) = c(2,2)
dimnames(C) = list("C" = c("C0", "C1"), "U" = c("U0","U1"))

A = matrix(c(1,0,0.2,0.8), nrow = 2, ncol = 2)
dim(A) = c(2,2)
dimnames(A) = list("A" = c("A0", "A1"), "C" = c("C0", "C1"))

B = matrix(c(1,0,0.2,0.8), nrow = 2, ncol = 2)
dim(B) = c(2,2)
dimnames(B) = list("B" = c("B0", "B1"), "C" = c("C0", "C1"))

D = matrix(c(0.9, #000
             0.1, #100
             0,   #010
             1,   #110
             0,   #001
             1,   #101
             0,   #011
             1),  #111
           nrow = 2, ncol = 4)
dim(D) = c(2,2,2)
dimnames(D) = list("D"=c("D0", "D1"), "A" = c("A0", "A1"), "B" = c("B0", "B1"))

Ch = matrix(c(0.9,0.1,0.1,0.9), nrow = 2, ncol=2)
dim(Ch) = c(2,2)
dimnames(Ch) = list("Ch" = c("C0", "C1"), "U" = c("U0","U1"))

Ah = matrix(c(1,0,0.2,0.8), nrow = 2, ncol = 2)
dim(Ah) = c(2,2)
dimnames(Ah) = list("Ah" = c("A0", "A1"), "Ch" = c("C0", "C1"))

Bh = matrix(c(1,0,0.2,0.8), nrow = 2, ncol = 2)
dim(Bh) = c(2,2)
dimnames(Bh) = list("Bh" = c("B0", "B1"), "Ch" = c("C0", "C1"))

Dh = matrix(c(0.9, #000
             0.1, #100
             0,   #010
             1,   #110
             0,   #001
             1,   #101
             0,   #011
             1),  #111
           nrow = 2, ncol = 4)
dim(Dh) = c(2,2,2)
dimnames(Dh) = list("Dh"=c("D0", "D1"), "Ah" = c("A0", "A1"), "Bh" = c("B0", "B1"))

fit = custom.fit(both, list(U = U, Ch = Ch, Ah = Ah, Bh = Bh, Dh = Dh, C = C, A = A, B = B, D = D))
fitcom = compile(as.grain(fit))

evidence = setEvidence(fitcom, evidence = list(D = "1", Ah = "0"))
querygrain(evidence, "Dh")
```

### 2

```{r}
set.seed(1)
library(HMM)
set.seed(1)
states = 1:10
symbols = 1:5
start_probs = c(1/5, 0, 1/5, 0, 0, 1/5, 0, 1/5, 1/5, 0)

# Define the transition probabilities
trans_probs <- matrix(c(
  #1a  #1b  #2a  #2b  #2c  #3a  #3b  #4a  #5a  #5b
    0,   1,   0,   0,   0,   0,   0,   0,   0,   0,  #1a
    0,   0.5, 0.5, 0,   0,   0,   0,   0,   0,   0,  #1b
    0,   0,   0,   1,   0,   0,   0,   0,   0,   0,  #2a
    0,   0,   0,   0,   1,   0,   0,   0,   0,   0,  #2b
    0,   0,   0,   0,   0.5, 0.5, 0,   0,   0,   0,  #2c
    0,   0,   0,   0,   0,   0,   1,   0,   0,   0,  #3a
    0,   0,   0,   0,   0,   0,   .5,  .5,  0,   0,  #3b
    0,   0,   0,   0,   0,   0,   0,   .5,  .5,  0,  #4a
    0,   0,   0,   0,   0,   0,   0,   0,   0,   1,  #5a
    .5,  0,   0,   0,   0,   0,   0,   0,   0,   .5  #5b
), nrow = length(states), ncol = length(states), byrow = TRUE)

# Define the emission probabilities
emission_probs = matrix(c(
   #1     #2     #3   #4   #5
    1/3,   1/3,   0,   0,   1/3, #1a
    1/3,   1/3,   0,   0,   1/3, #1b
    1/3,   1/3,   1/3, 0,   0,   #2a
    1/3,   1/3,   1/3, 0,   0,   #2b
    1/3,   1/3,   1/3, 0,   0,   #2c
    0,     1/3,   1/3, 1/3, 0,   #3a
    0,     1/3,   1/3, 1/3, 0,   #3b
    0,     0,     1/3, 1/3, 1/3, #4a
    1/3,   0,     0,   1/3, 1/3, #5a
    1/3,   0,     0,   1/3, 1/3 #5b
), nrow = length(states), ncol = length(symbols), byrow = TRUE)

hmm_model = initHMM(States=states, Symbols=symbols, startProbs=start_probs,
transProbs=trans_probs, emissionProbs=emission_probs)
hmm_model

simHMM(hmm_model, 100)
```
### 3
In the algorithm, note that S+ represents all the states and S all the non-terminal states. 
```{r}
rm(list=ls())
set.seed(1)

# Value Iteration Algorithm
value_iteration = function(theta=0.1, gamma=0.95){
  pi = rep(-1, 10)
  V = runif(9)
  V[10] = 0
  
  repeat{
    delta = 0
    for (s in 1:9){
      v = V[s]
      max_A = 0
      V[s] <- max(gamma*V[s],(s+1==10)+gamma*V[s+1])
      delta = max(delta, abs(v-V[s]))
    }
    
    if(delta < theta){
      break
    }
  }

  for (s in 1:9) {
    pi[s] = which.max(c(gamma*V[s],(s+1==10)+gamma*V[s+1]))
  }
  
  return(list(pi=pi, V = V))
}

value_iteration()
```

### 4
```{r}
rm(list=ls())
set.seed(1)

SquareExponential <- function(sigmaf, ell)
{
  rval <- function(x, y = NULL) {
    n1 <- length(x)
    n2 <- length(y)
    k <- matrix(NA,n1,n2)
    for (i in 1:n2){
      k[,i] <- sigmaf**2*exp(-0.5*( (x-y[i])/ell)**2 )
    }
    return(k)
  }
  class(rval) <- "kernel"
  return(rval)
}

periodic <- function(sigmaf, ell1, ell2, d) {
    rval <- function(x1, y = NULL) {
      n1 <- length(x1)
      n2 <- length(y)
      K <- matrix(NA,n1,n2)
      for (i in 1:n1){
        for (j in 1:n2){
          r = sqrt(crossprod(x1[i]-y[j]))
          factor1 = sigmaf**2*exp(-0.5*r**2/ell2**2)
          factor2 = exp(-2*(sin(pi*r/d)**2)/ell1**2)
          K[i,j] <- factor1*factor2
        }
      }
      return(K)
    }
    
  class(rval) <- "kernel"
  return(rval)
} 

square_kernel = SquareExponential(sigmaf = 20, ell = 100)
periodic_kernel = periodic(sigmaf = 20, ell1 = 1, ell2 = 100, d =365)

X = c(1, 182, 365)

square_kernel(X, X)
periodic_kernel(X, X)
```
Q: Discuss the results.
A: We see that points further apart have a lower kernel-value.